FROM alpine:3.20

RUN apk add --no-cache bash curl jq bats tini kubectl --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing

COPY test/e2e /app/test/e2e

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["sleep", "infinity"]
