apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: multi-k8s-auth

build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: multi-k8s-auth
    docker:
      dockerfile: Dockerfile
  - image: multi-k8s-auth-test
    docker:
      dockerfile: Dockerfile.test

profiles:
- name: cluster-a
  deploy:
    kubeContext: kind-cluster-a
    helm:
      releases:
      - name: multi-k8s-auth
        createNamespace: true
        namespace: multi-k8s-auth
        chartPath: k8s/cluster-a
        setValueTemplates:
          cluster_b.api_server: https://{{.CLUSTER_B_IP}}:6443
          cluster_b.issuer: "{{.ISSUER}}"
          cluster_b.bootstrap_token: "{{.BOOTSTRAP_TOKEN}}"
          cluster_b.ca_cert: "{{.CA_CERT}}"
          cluster_b.create_secret: "{{.CREATE_SECRET}}"
- name: cluster-b
  deploy:
    kubeContext: kind-cluster-b
    helm:
      releases:
      - name: multi-k8s-auth-remote
        createNamespace: true
        namespace: multi-k8s-auth
        chartPath: k8s/cluster-b

