apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: kube-federated-auth

profiles:
- name: cluster-a
  build:
    tagPolicy:
      gitCommit:
        variant: Tags
    local:
      push: false
      useBuildkit: true
    artifacts:
    - image: kube-federated-auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VERSION: "{{.IMAGE_TAG}}"
    - image: kube-federated-auth-test
      docker:
        dockerfile: Dockerfile.test
    - image: kube-auth-proxy
      docker:
        dockerfile: Dockerfile.proxy
        buildArgs:
          VERSION: "{{.IMAGE_TAG}}"
  deploy:
    kubeContext: kind-cluster-a
    helm:
      releases:
      - name: kube-federated-auth
        createNamespace: true
        namespace: kube-federated-auth
        chartPath: k8s/cluster-a
        setValueTemplates:
          cluster_b.api_server: https://{{.CLUSTER_B_IP}}:6443
          cluster_b.issuer: "{{.ISSUER}}"
- name: cluster-b
  deploy:
    kubeContext: kind-cluster-b
    helm:
      releases:
      - name: kube-federated-auth-remote
        createNamespace: true
        namespace: kube-federated-auth
        chartPath: k8s/cluster-b
- name: proxy
  build:
    tagPolicy:
      gitCommit:
        variant: Tags
    local:
      push: false
      useBuildkit: true
    artifacts:
    - image: kube-auth-proxy
      docker:
        dockerfile: Dockerfile.proxy
        buildArgs:
          VERSION: "{{.IMAGE_TAG}}"
  deploy:
    kubeContext: kind-cluster-a
    helm:
      releases:
      - name: kube-auth-proxy
        createNamespace: true
        namespace: kube-federated-auth
        chartPath: k8s/kube-auth-proxy
- name: proxy-incluster
  build:
    tagPolicy:
      gitCommit:
        variant: Tags
    local:
      push: false
      useBuildkit: true
    artifacts:
    - image: kube-auth-proxy
      docker:
        dockerfile: Dockerfile.proxy
        buildArgs:
          VERSION: "{{.IMAGE_TAG}}"
  deploy:
    kubeContext: kind-cluster-a
    helm:
      releases:
      - name: kube-auth-proxy-incluster
        createNamespace: true
        namespace: kube-federated-auth
        chartPath: k8s/kube-auth-proxy
        setValues:
          tokenReviewURL: ""

