apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: multi-k8s-auth

build:
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    sha256: {}
  artifacts:
  - image: multi-k8s-auth
    docker:
      dockerfile: Dockerfile
  - image: multi-k8s-auth-test
    docker:
      dockerfile: Dockerfile.test

deploy:
  kubeContext: kind-cluster-a
  kubectl: {}

manifests:
  rawYaml:
  - k8s/cluster-a/namespace.yaml
  - k8s/cluster-a/serviceaccount.yaml
  # configmap.yaml is created by setup-multicluster.sh with dynamic cluster-b config
  - k8s/cluster-a/deployment.yaml
  - k8s/cluster-a/service.yaml
  - k8s/cluster-a/test-client.yaml

---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cluster-b

build:
  artifacts: []

deploy:
  kubeContext: kind-cluster-b
  kubectl: {}

manifests:
  rawYaml:
  - k8s/cluster-b/namespace.yaml
  - k8s/cluster-b/test-client.yaml
